---
apiVersion: "v1"
kind: "PersistentVolume"
metadata: 
  name: "pv-gitlab-config"
spec: 
  capacity: 
    storage: "1Gi"
  accessModes: 
    - "ReadWriteOnce"
  nfs: 
    path: "/exports/gitlab/config"
    server: "nfs"
---
apiVersion: "v1"
kind: "PersistentVolume"
metadata:   
  name: "pv-gitlab-logs"
spec:   
  capacity:   
    storage: "2Gi"
  accessModes:   
    - "ReadWriteOnce"
  nfs:   
    path: "/exports/gitlab/logs"
    server: "nfs"
---
apiVersion: "v1"
kind: "PersistentVolume"
metadata:   
  name: "pv-gitlab-data"
spec:   
  capacity:   
    storage: "20Gi"
  accessModes:   
    - "ReadWriteOnce"
  nfs:   
    path: "/exports/gitlab/data"
    server: "nfs"
